server:
  port : 8090
  error:    include-message: always


spring:
  application:    name: POKEMON-SERVICE    


eureka:  client:    register-with-eureka: true    fetch-registry: true 
    service-url:      defaultZone: http://localhost:8761/eureka/
  instance:    hostname: localhost    